// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.1
// source: example/v1/error_reason.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_RECORD_NOT_FOUND      ErrorReason = 0
	ErrorReason_RECORD_ALREADY_EXISTS ErrorReason = 1
	ErrorReason_BAD_REQUEST           ErrorReason = 2
	ErrorReason_SYSTEM_ERROR          ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "RECORD_NOT_FOUND",
		1: "RECORD_ALREADY_EXISTS",
		2: "BAD_REQUEST",
		3: "SYSTEM_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"RECORD_NOT_FOUND":      0,
		"RECORD_ALREADY_EXISTS": 1,
		"BAD_REQUEST":           2,
		"SYSTEM_ERROR":          3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_example_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_example_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_example_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_example_v1_error_reason_proto protoreflect.FileDescriptor

const file_example_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dexample/v1/error_reason.proto\x12\n" +
	"v1.example\x1a\x13errors/errors.proto*\x7f\n" +
	"\vErrorReason\x12\x1a\n" +
	"\x10RECORD_NOT_FOUND\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1f\n" +
	"\x15RECORD_ALREADY_EXISTS\x10\x01\x1a\x04\xa8E\x90\x03\x12\x15\n" +
	"\vBAD_REQUEST\x10\x02\x1a\x04\xa8E\x90\x03\x12\x16\n" +
	"\fSYSTEM_ERROR\x10\x03\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B,Z*github.com/itsgn/sgn-layout/api/example/v1b\x06proto3"

var (
	file_example_v1_error_reason_proto_rawDescOnce sync.Once
	file_example_v1_error_reason_proto_rawDescData []byte
)

func file_example_v1_error_reason_proto_rawDescGZIP() []byte {
	file_example_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_example_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_v1_error_reason_proto_rawDesc), len(file_example_v1_error_reason_proto_rawDesc)))
	})
	return file_example_v1_error_reason_proto_rawDescData
}

var file_example_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: v1.example.ErrorReason
}
var file_example_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_example_v1_error_reason_proto_init() }
func file_example_v1_error_reason_proto_init() {
	if File_example_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_v1_error_reason_proto_rawDesc), len(file_example_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_example_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_example_v1_error_reason_proto_enumTypes,
	}.Build()
	File_example_v1_error_reason_proto = out.File
	file_example_v1_error_reason_proto_goTypes = nil
	file_example_v1_error_reason_proto_depIdxs = nil
}
