// Code generated by entproto. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.1
// source: example/v1/example.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request - Update
type UpdateExampleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary key id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// state
	Status        bool `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateExampleReq) Reset() {
	*x = UpdateExampleReq{}
	mi := &file_example_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateExampleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateExampleReq) ProtoMessage() {}

func (x *UpdateExampleReq) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateExampleReq.ProtoReflect.Descriptor instead.
func (*UpdateExampleReq) Descriptor() ([]byte, []int) {
	return file_example_v1_example_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateExampleReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateExampleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateExampleReq) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Request - Create
type CreateExampleReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExampleReq) Reset() {
	*x = CreateExampleReq{}
	mi := &file_example_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExampleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExampleReq) ProtoMessage() {}

func (x *CreateExampleReq) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExampleReq.ProtoReflect.Descriptor instead.
func (*CreateExampleReq) Descriptor() ([]byte, []int) {
	return file_example_v1_example_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExampleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateExampleReq) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Response - Sample message
type Example struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary key id
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// name
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// state
	Status bool `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// creation time
	CreatedAt string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Update time
	UpdatedAt string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Delete time
	DeletedAt     string `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Example) Reset() {
	*x = Example{}
	mi := &file_example_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Example) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Example) ProtoMessage() {}

func (x *Example) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Example.ProtoReflect.Descriptor instead.
func (*Example) Descriptor() ([]byte, []int) {
	return file_example_v1_example_proto_rawDescGZIP(), []int{2}
}

func (x *Example) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Example) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Example) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Example) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Example) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Example) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// Response - Pagination
type GetExampleListPageRes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// total
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// list
	List          []*Example `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleListPageRes) Reset() {
	*x = GetExampleListPageRes{}
	mi := &file_example_v1_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleListPageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleListPageRes) ProtoMessage() {}

func (x *GetExampleListPageRes) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleListPageRes.ProtoReflect.Descriptor instead.
func (*GetExampleListPageRes) Descriptor() ([]byte, []int) {
	return file_example_v1_example_proto_rawDescGZIP(), []int{3}
}

func (x *GetExampleListPageRes) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetExampleListPageRes) GetList() []*Example {
	if x != nil {
		return x.List
	}
	return nil
}

// Requests - Paginated List
type GetExampleListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary key id
	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Number of page records
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// name
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Status true normal false frozen
	Status *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	// Whether to delete
	IsDeleted *wrapperspb.BoolValue `protobuf:"bytes,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	// Creation start time
	CreatedAtStart string `protobuf:"bytes,6,opt,name=created_at_start,json=createdAtStart,proto3" json:"created_at_start,omitempty"`
	// Creation end time
	CreatedAtEnd  string `protobuf:"bytes,7,opt,name=created_at_end,json=createdAtEnd,proto3" json:"created_at_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExampleListReq) Reset() {
	*x = GetExampleListReq{}
	mi := &file_example_v1_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExampleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExampleListReq) ProtoMessage() {}

func (x *GetExampleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExampleListReq.ProtoReflect.Descriptor instead.
func (*GetExampleListReq) Descriptor() ([]byte, []int) {
	return file_example_v1_example_proto_rawDescGZIP(), []int{4}
}

func (x *GetExampleListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetExampleListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetExampleListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetExampleListReq) GetStatus() *wrapperspb.BoolValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GetExampleListReq) GetIsDeleted() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsDeleted
	}
	return nil
}

func (x *GetExampleListReq) GetCreatedAtStart() string {
	if x != nil {
		return x.CreatedAtStart
	}
	return ""
}

func (x *GetExampleListReq) GetCreatedAtEnd() string {
	if x != nil {
		return x.CreatedAtEnd
	}
	return ""
}

// Request - Primary key id
type ExampleIdReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// primary key id
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExampleIdReq) Reset() {
	*x = ExampleIdReq{}
	mi := &file_example_v1_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExampleIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleIdReq) ProtoMessage() {}

func (x *ExampleIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_example_v1_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleIdReq.ProtoReflect.Descriptor instead.
func (*ExampleIdReq) Descriptor() ([]byte, []int) {
	return file_example_v1_example_proto_rawDescGZIP(), []int{5}
}

func (x *ExampleIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_example_v1_example_proto protoreflect.FileDescriptor

const file_example_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x18example/v1/example.proto\x12\n" +
	"example.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1bopenapiv3/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"b\n" +
	"\x10UpdateExampleReq\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x1d\n" +
	"\x04name\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"I\n" +
	"\x10CreateExampleReq\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18<R\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status\"\xa2\x01\n" +
	"\aExample\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\tR\tdeletedAt\"V\n" +
	"\x15GetExampleListPageRes\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12'\n" +
	"\x04list\x18\x02 \x03(\v2\x13.example.v1.ExampleR\x04list\"\xa8\x02\n" +
	"\x11GetExampleListReq\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x04page\x12#\n" +
	"\bpageSize\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\x06status\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\x06status\x129\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\tisDeleted\x12(\n" +
	"\x10created_at_start\x18\x06 \x01(\tR\x0ecreatedAtStart\x12$\n" +
	"\x0ecreated_at_end\x18\a \x01(\tR\fcreatedAtEnd\"\x1e\n" +
	"\fExampleIdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xad\x04\n" +
	"\x0eExampleService\x12d\n" +
	"\x0eGetExampleList\x12\x1d.example.v1.GetExampleListReq\x1a!.example.v1.GetExampleListPageRes\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/example\x12R\n" +
	"\n" +
	"GetExample\x12\x18.example.v1.ExampleIdReq\x1a\x13.example.v1.Example\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/example/{id}\x12W\n" +
	"\rCreateExample\x12\x1c.example.v1.CreateExampleReq\x1a\x13.example.v1.Example\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/example\x12Z\n" +
	"\rUpdateExample\x12\x1c.example.v1.UpdateExampleReq\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\x1a\b/example\x12S\n" +
	"\rDeleteExample\x12\x18.example.v1.ExampleIdReq\x1a\x16.google.protobuf.Empty\"\x10\x82\xd3\xe4\x93\x02\n" +
	"*\b/example\x12W\n" +
	"\x0eRecoverExample\x12\x18.example.v1.ExampleIdReq\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r:\x01*2\b/exampleBe\xbaG6\x124\n" +
	"\x0eSample service\x12\x0eSample service\"\v\n" +
	"\tyour name2\x050.0.1Z*github.com/itsgn/sgn-layout/api/example/v1b\x06proto3"

var (
	file_example_v1_example_proto_rawDescOnce sync.Once
	file_example_v1_example_proto_rawDescData []byte
)

func file_example_v1_example_proto_rawDescGZIP() []byte {
	file_example_v1_example_proto_rawDescOnce.Do(func() {
		file_example_v1_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_v1_example_proto_rawDesc), len(file_example_v1_example_proto_rawDesc)))
	})
	return file_example_v1_example_proto_rawDescData
}

var file_example_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_example_v1_example_proto_goTypes = []any{
	(*UpdateExampleReq)(nil),      // 0: example.v1.UpdateExampleReq
	(*CreateExampleReq)(nil),      // 1: example.v1.CreateExampleReq
	(*Example)(nil),               // 2: example.v1.Example
	(*GetExampleListPageRes)(nil), // 3: example.v1.GetExampleListPageRes
	(*GetExampleListReq)(nil),     // 4: example.v1.GetExampleListReq
	(*ExampleIdReq)(nil),          // 5: example.v1.ExampleIdReq
	(*wrapperspb.BoolValue)(nil),  // 6: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_example_v1_example_proto_depIdxs = []int32{
	2, // 0: example.v1.GetExampleListPageRes.list:type_name -> example.v1.Example
	6, // 1: example.v1.GetExampleListReq.status:type_name -> google.protobuf.BoolValue
	6, // 2: example.v1.GetExampleListReq.is_deleted:type_name -> google.protobuf.BoolValue
	4, // 3: example.v1.ExampleService.GetExampleList:input_type -> example.v1.GetExampleListReq
	5, // 4: example.v1.ExampleService.GetExample:input_type -> example.v1.ExampleIdReq
	1, // 5: example.v1.ExampleService.CreateExample:input_type -> example.v1.CreateExampleReq
	0, // 6: example.v1.ExampleService.UpdateExample:input_type -> example.v1.UpdateExampleReq
	5, // 7: example.v1.ExampleService.DeleteExample:input_type -> example.v1.ExampleIdReq
	5, // 8: example.v1.ExampleService.RecoverExample:input_type -> example.v1.ExampleIdReq
	3, // 9: example.v1.ExampleService.GetExampleList:output_type -> example.v1.GetExampleListPageRes
	2, // 10: example.v1.ExampleService.GetExample:output_type -> example.v1.Example
	2, // 11: example.v1.ExampleService.CreateExample:output_type -> example.v1.Example
	7, // 12: example.v1.ExampleService.UpdateExample:output_type -> google.protobuf.Empty
	7, // 13: example.v1.ExampleService.DeleteExample:output_type -> google.protobuf.Empty
	7, // 14: example.v1.ExampleService.RecoverExample:output_type -> google.protobuf.Empty
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_v1_example_proto_init() }
func file_example_v1_example_proto_init() {
	if File_example_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_v1_example_proto_rawDesc), len(file_example_v1_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_v1_example_proto_goTypes,
		DependencyIndexes: file_example_v1_example_proto_depIdxs,
		MessageInfos:      file_example_v1_example_proto_msgTypes,
	}.Build()
	File_example_v1_example_proto = out.File
	file_example_v1_example_proto_goTypes = nil
	file_example_v1_example_proto_depIdxs = nil
}
