// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/it-sgn/sgn-layout/internal/biz"
	"github.com/it-sgn/sgn-layout/internal/conf"
	"github.com/it-sgn/sgn-layout/internal/data"
	"github.com/it-sgn/sgn-layout/internal/server"
	"github.com/it-sgn/sgn-layout/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
//
//	func wireApp(*conf.Env, *conf.Server, *conf.Data, *conf.Bootstrap, log.Logger, *conf.Registry, *conf.Trace) (*kratos.App, func(), error) {
//		panic(wire.Build(server.ProviderSet, data.ProviderSet, biz.ProviderSet, service.ProviderSet, newApp))
//	}
//
//	func wireApp(*conf.Env, *conf.Server, *conf.Data, *conf.Bootstrap, log.Logger, *conf.Registry, *conf.Trace) (*kratos.App, func(), error) {
//		panic(wire.Build(server.ProviderSet, data.ProviderSet, biz.ProviderSet, service.ProviderSet, newApp))
//	}
func wireApp(env *conf.Env, confServer *conf.Server, confData *conf.Data, bootstrap *conf.Bootstrap, logger log.Logger, registry *conf.Registry, trace *conf.Trace) (*kratos.App, func(), error) {
	db := data.NewMysqlCmd(bootstrap, logger)
	client := data.NewRedisClient(confData)
	dataData, cleanup, err := data.NewData(bootstrap, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	exampleRepo := data.NewExampleRepo(dataData, logger)
	exampleUsecase := biz.NewExampleUsecase(exampleRepo, logger)
	exampleService := service.NewExampleService(exampleUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, exampleService, trace, logger)
	httpServer := server.NewHTTPServer(bootstrap, confServer, trace,exampleService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
